# Generated by Django 5.1.6 on 2025-03-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageupload",
            name="name",
            field=models.TextField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="imageupload",
            name="tag",
            field=models.CharField(
                choices=[
                    ("philosophical", "Философское"),
                    ("funny", "Смешное"),
                    ("inspirational", "Жизнеутверждающее"),
                ],
                default="philosophical",
                max_length=20,
            ),
        ),
    ]
