# Generated by Django 5.1.6 on 2025-03-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catapp", "0002_imageupload_name_imageupload_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="avatar",
        ),
        migrations.AlterField(
            model_name="imageupload",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="imageupload",
            name="name",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="imageupload",
            name="tag",
            field=models.CharField(
                choices=[
                    ("philosophical", "Философское"),
                    ("funny", "Смешное"),
                    ("inspirational", "Жизнеутверждающее"),
                    ("domestic", "Домашнее"),
                    ("relax", "Релакс"),
                    ("dreams", "Мечты"),
                    ("trivial", "Мелочи"),
                    ("nostalgia", "Ностальгия"),
                    ("mysterious", "Загадочное"),
                    ("fate", "Судьба"),
                    ("everyday", "Бытовое"),
                ],
                default="philosophical",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prediction",
            name="tag",
            field=models.CharField(
                choices=[
                    ("philosophical", "Философское"),
                    ("funny", "Смешное"),
                    ("inspirational", "Жизнеутверждающее"),
                    ("domestic", "Домашнее"),
                    ("relax", "Релакс"),
                    ("dreams", "Мечты"),
                    ("trivial", "Мелочи"),
                    ("nostalgia", "Ностальгия"),
                    ("mysterious", "Загадочное"),
                    ("fate", "Судьба"),
                    ("everyday", "Бытовое"),
                ],
                default="philosophical",
                max_length=20,
            ),
        ),
    ]
