# Generated by Django 5.1.6 on 2025-03-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catapp", "0002_alter_prediction_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="avatar",
        ),
        migrations.AddField(
            model_name="imageupload",
            name="name",
            field=models.TextField(default="photo", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imageupload",
            name="tag",
            field=models.CharField(
                choices=[
                    ("philosophical", "Философское"),
                    ("funny", "Смешное"),
                    ("inspirational", "Жизнеутверждающее"),
                    ("domestic", "Домашнее"),
                    ("relax", "Релакс"),
                    ("dreams", "Мечты"),
                    ("trivial", "Мелочи"),
                    ("nostalgia", "Ностальгия"),
                    ("mysterious", "Загадочное"),
                    ("fate", "Судьба"),
                    ("everyday", "Бытовое"),
                ],
                default="philosophical",
                max_length=20,
            ),
        ),
    ]
