# Generated by Django 5.1.6 on 2025-03-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catapp", "0003_remove_comment_avatar_imageupload_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageupload",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
